from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class IntentDomain(str, Enum):
    PROFILE_IDENTITY = "PROFILE_IDENTITY"
    PROFILE_EDUCATION = "PROFILE_EDUCATION"
    PROFILE_PROJECTS = "PROFILE_PROJECTS"
    PROFILE_INTERESTS = "PROFILE_INTERESTS"
    PROFILE_CAREER = "PROFILE_CAREER"
    LOCATION = "LOCATION"
    MAPS_DIRECTIONS = "MAPS_DIRECTIONS"
    SYSTEM_METRICS = "SYSTEM_METRICS"
    SYSTEM_STATUS = "SYSTEM_STATUS"
    OLLAMA_STATUS = "OLLAMA_STATUS"
    FILESYSTEM_SEARCH = "FILESYSTEM_SEARCH"
    FILESYSTEM_READ = "FILESYSTEM_READ"
    FILESYSTEM_EDIT = "FILESYSTEM_EDIT"
    DESKTOP_ACTION = "DESKTOP_ACTION"
    PROCESS_MANAGEMENT = "PROCESS_MANAGEMENT"
    TERMINAL_ACTION = "TERMINAL_ACTION"
    SCREEN_INSPECTION = "SCREEN_INSPECTION"
    START_LIVE_DESKTOP_MONITORING = "START_LIVE_DESKTOP_MONITORING"
    STOP_LIVE_DESKTOP_MONITORING = "STOP_LIVE_DESKTOP_MONITORING"
    PAUSE_LIVE_DESKTOP_MONITORING = "PAUSE_LIVE_DESKTOP_MONITORING"
    RESUME_LIVE_DESKTOP_MONITORING = "RESUME_LIVE_DESKTOP_MONITORING"
    QUERY_LIVE_DESKTOP_STATE = "QUERY_LIVE_DESKTOP_STATE"
    WATCH_WINDOW = "WATCH_WINDOW"
    WATCH_CONDITION = "WATCH_CONDITION"
    QUERY_CURSOR_TARGET = "QUERY_CURSOR_TARGET"
    MEMORY = "MEMORY"
    GENERAL_CHAT = "GENERAL_CHAT"


class IntentItem(BaseModel):
    domain: IntentDomain
    confidence: float = 0.99
    entities: Dict[str, Any] = Field(default_factory=dict)
    priority: int = 1


class IntentPlan(BaseModel):
    channel: str = "chat"  # "chat" | "voice"
    original_text: str
    normalized_text: str
    intents: List[IntentItem] = Field(default_factory=list)
