import json
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional, AsyncGenerator
import httpx
from app.core.config import settings
from app.core.exceptions import LLMProviderError, LLMTimeoutError
from app.core.logging import logger


class LLMProvider(ABC):
    """Abstract base class interface for all LLM providers."""

    @abstractmethod
    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        """Generates a text completion response for given messages."""
        pass

    async def generate_response_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> AsyncGenerator[str, None]:
        """Yields text chunks as they are generated by the LLM provider."""
        full_text = await self.generate_response(messages, model=model, timeout=timeout)
        yield full_text


class MockLLMProvider(LLMProvider):
    """Mock LLM provider for unit testing and offline development."""

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        user_message = ""
        for msg in reversed(messages):
            if msg.get("role") == "user":
                user_message = msg.get("content", "")
                break

        logger.info(f"[MockLLMProvider] Processing message: {user_message[:50]}...")
        if "error" in user_message.lower():
            raise LLMProviderError("mock", "Simulated mock provider failure")

        return f"Mock response from JARVIS to: '{user_message}'"

    async def generate_response_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> AsyncGenerator[str, None]:
        full_text = await self.generate_response(messages, model=model, timeout=timeout)
        chunks = full_text.split(" ")
        for i, chunk in enumerate(chunks):
            yield chunk + (" " if i < len(chunks) - 1 else "")


class OpenAILLMProvider(LLMProvider):
    """OpenAI and OpenAI-compatible API provider via HTTPX."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.LLM_API_KEY
        self.base_url = "https://api.openai.com/v1/chat/completions"

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        if not self.api_key:
            raise LLMProviderError("openai", "LLM_API_KEY environment variable is not configured.")

        selected_model = model or settings.LLM_MODEL
        req_timeout = timeout or settings.LLM_TIMEOUT

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": selected_model,
            "messages": messages,
        }

        try:
            async with httpx.AsyncClient(timeout=req_timeout) as client:
                response = await client.post(self.base_url, headers=headers, json=payload)
                if response.status_code != 200:
                    raise LLMProviderError("openai", f"HTTP {response.status_code}: {response.text}")
                data = response.json()
                return data["choices"][0]["message"]["content"]
        except httpx.TimeoutException:
            raise LLMTimeoutError("openai")
        except httpx.RequestError as exc:
            raise LLMProviderError("openai", f"Network request error: {str(exc)}")


class GeminiLLMProvider(LLMProvider):
    """Google Gemini API provider via HTTPX REST interface."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.LLM_API_KEY

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        if not self.api_key:
            raise LLMProviderError("gemini", "LLM_API_KEY environment variable is not configured.")

        selected_model = model or settings.LLM_MODEL or "gemini-1.5-flash"
        req_timeout = timeout or settings.LLM_TIMEOUT

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{selected_model}:generateContent?key={self.api_key}"

        contents = []
        for msg in messages:
            role = "user" if msg["role"] == "user" else "model"
            if msg["role"] == "system":
                continue
            contents.append({
                "role": role,
                "parts": [{"text": msg["content"]}],
            })

        payload = {"contents": contents}

        try:
            async with httpx.AsyncClient(timeout=req_timeout) as client:
                response = await client.post(url, json=payload)
                if response.status_code != 200:
                    raise LLMProviderError("gemini", f"HTTP {response.status_code}: {response.text}")
                data = response.json()
                return data["candidates"][0]["content"]["parts"][0]["text"]
        except httpx.TimeoutException:
            raise LLMTimeoutError("gemini")
        except httpx.RequestError as exc:
            raise LLMProviderError("gemini", f"Network request error: {str(exc)}")


class OllamaLLMProvider(LLMProvider):
    """Local Ollama LLM provider via async HTTP API with explicit timeouts."""

    def __init__(self, base_url: Optional[str] = None):
        self.base_url = (base_url or settings.OLLAMA_BASE_URL).rstrip("/")
        self.endpoint = f"{self.base_url}/api/chat"

    def _get_httpx_timeout(self, override_timeout: Optional[float] = None) -> httpx.Timeout:
        read_t = override_timeout or settings.OLLAMA_READ_TIMEOUT
        return httpx.Timeout(
            connect=settings.OLLAMA_CONNECT_TIMEOUT,
            read=read_t,
            write=10.0,
            pool=10.0,
        )

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        selected_model = model or settings.OLLAMA_MODEL
        req_timeout = self._get_httpx_timeout(timeout)

        payload = {
            "model": selected_model,
            "messages": messages,
            "stream": False,
            "options": {
                "num_ctx": getattr(settings, "OLLAMA_CONTEXT_LENGTH", 16384)
            },
        }

        try:
            async with httpx.AsyncClient(timeout=req_timeout) as client:
                response = await client.post(self.endpoint, json=payload)

                if response.status_code == 404:
                    raise LLMProviderError("ollama", f"Model '{selected_model}' not found on Ollama server.")
                elif response.status_code != 200:
                    raise LLMProviderError("ollama", f"HTTP {response.status_code}: {response.text}")

                try:
                    data = response.json()
                    return data["message"]["content"]
                except (KeyError, TypeError) as exc:
                    raise LLMProviderError("ollama", f"Malformed response structure from Ollama API: {str(exc)}")

        except httpx.TimeoutException:
            raise LLMTimeoutError("ollama")
        except LLMProviderError:
            raise
        except httpx.RequestError as exc:
            raise LLMProviderError(
                "ollama", f"Ollama server is unavailable at {self.base_url}: {str(exc)}"
            )

    async def generate_response_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> AsyncGenerator[str, None]:
        selected_model = model or settings.OLLAMA_MODEL
        req_timeout = self._get_httpx_timeout(timeout)

        payload = {
            "model": selected_model,
            "messages": messages,
            "stream": True,
            "options": {
                "num_ctx": getattr(settings, "OLLAMA_CONTEXT_LENGTH", 16384)
            },
            "keep_alive": "10m",
        }

        logger.info(f"[OllamaStream] Starting model={selected_model}")
        first_chunk_logged = False
        chunk_count = 0
        char_count = 0

        try:
            async with httpx.AsyncClient(timeout=req_timeout) as client:
                async with client.stream("POST", self.endpoint, json=payload) as response:
                    if response.status_code == 404:
                        raise LLMProviderError("ollama", f"Model '{selected_model}' not found on Ollama server.")
                    elif response.status_code != 200:
                        content = await response.aread()
                        raise LLMProviderError("ollama", f"HTTP {response.status_code}: {content.decode()}")

                    async for line in response.aiter_lines():
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            data = json.loads(line)
                        except json.JSONDecodeError:
                            continue

                        msg_data = data.get("message", {})
                        chunk = msg_data.get("content") or data.get("thinking") or msg_data.get("thinking") or ""

                        if chunk:
                            if not first_chunk_logged:
                                logger.info("[OllamaStream] First chunk received")
                                first_chunk_logged = True
                            chunk_count += 1
                            char_count += len(chunk)
                            yield chunk

                        if data.get("done", False):
                            break

            logger.info(f"[OllamaStream] Stream completed chunks={chunk_count} characters={char_count}")

        except httpx.TimeoutException:
            raise LLMTimeoutError("ollama")
        except LLMProviderError:
            raise
        except httpx.RequestError as exc:
            raise LLMProviderError(
                "ollama", f"Ollama server is unavailable at {self.base_url}: {str(exc)}"
            )


class LLMManager:
    """Factory and router for LLM Provider instances."""

    _providers = {
        "mock": MockLLMProvider,
        "openai": OpenAILLMProvider,
        "gemini": GeminiLLMProvider,
        "ollama": OllamaLLMProvider,
    }

    def __init__(self, provider_name: Optional[str] = None):
        self.provider_name = (provider_name or settings.LLM_PROVIDER).lower()
        self.provider = self._get_provider(self.provider_name)

    def _get_provider(self, provider_name: str) -> LLMProvider:
        provider_cls = self._providers.get(provider_name)
        if not provider_cls:
            logger.warning(f"Unknown provider '{provider_name}'. Falling back to MockLLMProvider.")
            return MockLLMProvider()
        return provider_cls()

    async def generate(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        """Routes text generation call to the configured provider."""
        return await self.provider.generate_response(messages, model=model, timeout=timeout)

    async def generate_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> AsyncGenerator[str, None]:
        """Routes text generation streaming call to the configured provider."""
        async for chunk in self.provider.generate_response_stream(messages, model=model, timeout=timeout):
            yield chunk
