import json
import time
import asyncio
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional, AsyncGenerator
import httpx
from app.core.config import settings
from app.core.exceptions import LLMProviderError, LLMTimeoutError
from app.core.logging import logger


class LLMProvider(ABC):
    """Abstract base class interface for all LLM providers."""

    @abstractmethod
    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        """Generates a text completion response for given messages."""
        pass

    async def generate_response_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
        cancel_event: Optional[asyncio.Event] = None,
    ) -> AsyncGenerator[str, None]:
        """Yields text chunks as they are generated by the LLM provider."""
        full_text = await self.generate_response(messages, model=model, timeout=timeout)
        yield full_text


class MockLLMProvider(LLMProvider):
    """Mock LLM provider for unit testing and offline development."""

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        user_message = ""
        for msg in reversed(messages):
            if msg.get("role") == "user":
                user_message = msg.get("content", "")
                break

        logger.info(f"[MockLLMProvider] Processing message: {user_message[:50]}...")
        if "error" in user_message.lower():
            raise LLMProviderError("mock", "Simulated mock provider failure")

        return f"Mock response from JARVIS to: '{user_message}'"

    async def generate_response_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
        cancel_event: Optional[asyncio.Event] = None,
    ) -> AsyncGenerator[str, None]:
        full_text = await self.generate_response(messages, model=model, timeout=timeout)
        chunks = full_text.split(" ")
        for i, chunk in enumerate(chunks):
            if cancel_event and cancel_event.is_set():
                logger.info("[MOCK CANCEL] Stream cancelled via cancel_event.")
                raise asyncio.CancelledError("Mock generation cancelled via barge-in")
            yield chunk + (" " if i < len(chunks) - 1 else "")


class OpenAILLMProvider(LLMProvider):
    """OpenAI and OpenAI-compatible API provider via HTTPX."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.LLM_API_KEY
        self.base_url = "https://api.openai.com/v1/chat/completions"

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        if not self.api_key:
            raise LLMProviderError("openai", "LLM_API_KEY environment variable is not configured.")

        selected_model = model or settings.LLM_MODEL
        req_timeout = timeout or settings.LLM_TIMEOUT

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": selected_model,
            "messages": messages,
        }

        try:
            async with httpx.AsyncClient(timeout=req_timeout) as client:
                response = await client.post(self.base_url, headers=headers, json=payload)
                if response.status_code != 200:
                    raise LLMProviderError("openai", f"HTTP {response.status_code}: {response.text}")
                data = response.json()
                return data["choices"][0]["message"]["content"]
        except httpx.TimeoutException:
            raise LLMTimeoutError("openai")
        except httpx.RequestError as exc:
            raise LLMProviderError("openai", f"Network request error: {str(exc)}")


class GeminiLLMProvider(LLMProvider):
    """Google Gemini API provider via HTTPX REST interface."""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or settings.LLM_API_KEY

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        if not self.api_key:
            raise LLMProviderError("gemini", "LLM_API_KEY environment variable is not configured.")

        selected_model = model or settings.LLM_MODEL or "gemini-1.5-flash"
        req_timeout = timeout or settings.LLM_TIMEOUT

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{selected_model}:generateContent?key={self.api_key}"

        contents = []
        for msg in messages:
            role = "user" if msg["role"] == "user" else "model"
            if msg["role"] == "system":
                continue
            contents.append({
                "role": role,
                "parts": [{"text": msg["content"]}],
            })

        payload = {"contents": contents}

        try:
            async with httpx.AsyncClient(timeout=req_timeout) as client:
                response = await client.post(url, json=payload)
                if response.status_code != 200:
                    raise LLMProviderError("gemini", f"HTTP {response.status_code}: {response.text}")
                data = response.json()
                return data["candidates"][0]["content"]["parts"][0]["text"]
        except httpx.TimeoutException:
            raise LLMTimeoutError("gemini")
        except httpx.RequestError as exc:
            raise LLMProviderError("gemini", f"Network request error: {str(exc)}")


class OllamaLLMProvider(LLMProvider):
    """Local Ollama LLM provider via async HTTP API with pre-flight health checks,
    streaming-backed response generation, model locks, and timing diagnostics.
    """

    _model_lock: Optional[asyncio.Lock] = None

    @classmethod
    def _get_lock(cls) -> asyncio.Lock:
        if cls._model_lock is None:
            cls._model_lock = asyncio.Lock()
        return cls._model_lock

    def __init__(self, base_url: Optional[str] = None):
        self.base_url = (base_url or settings.OLLAMA_BASE_URL).rstrip("/")
        self.endpoint = f"{self.base_url}/api/chat"

    def _get_httpx_timeout(self, override_timeout: Optional[float] = None) -> httpx.Timeout:
        read_t = override_timeout or settings.OLLAMA_READ_TIMEOUT
        return httpx.Timeout(
            connect=settings.OLLAMA_CONNECT_TIMEOUT,
            read=read_t,
            write=10.0,
            pool=10.0,
        )

    async def check_ollama_health(self, target_model: Optional[str] = None) -> Dict[str, Any]:
        """Pre-flight check to query GET /api/ps and verify Ollama server status and loaded models."""
        url = f"{self.base_url}/api/ps"
        model_name = target_model or settings.OLLAMA_MODEL
        timeout_cfg = httpx.Timeout(connect=2.0, read=3.0, write=2.0, pool=2.0)

        try:
            async with httpx.AsyncClient(timeout=timeout_cfg) as client:
                resp = await client.get(url)
                if resp.status_code == 200:
                    data = resp.json()
                    models = data.get("models", [])
                    loaded_names = [m.get("name") or m.get("model") for m in models]
                    is_target_loaded = any(model_name in name for name in loaded_names if name)
                    target_vram = 0
                    for m in models:
                        if model_name in (m.get("name") or m.get("model") or ""):
                            target_vram = m.get("size_vram", 0) or m.get("size", 0)

                    logger.info(
                        f"[OLLAMA PREFLIGHT] server_online=True target_model='{model_name}' "
                        f"is_loaded={is_target_loaded} loaded_count={len(models)} vram_bytes={target_vram}"
                    )
                    return {
                        "online": True,
                        "loaded_models": loaded_names,
                        "target_model": model_name,
                        "is_target_loaded": is_target_loaded,
                        "vram_bytes": target_vram,
                    }
                else:
                    logger.warning(f"[OLLAMA PREFLIGHT WARNING] GET /api/ps returned HTTP {resp.status_code}")
                    return {
                        "online": True,
                        "loaded_models": [],
                        "target_model": model_name,
                        "is_target_loaded": False,
                        "vram_bytes": 0,
                    }
        except Exception as exc:
            logger.warning(f"[OLLAMA PREFLIGHT WARNING] Could not query Ollama /api/ps: {type(exc).__name__}: {str(exc)}")
            return {
                "online": False,
                "loaded_models": [],
                "target_model": model_name,
                "is_target_loaded": False,
                "vram_bytes": 0,
                "error": str(exc),
            }

    async def generate_response(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        selected_model = model or settings.OLLAMA_MODEL
        num_ctx = getattr(settings, "OLLAMA_CONTEXT_LENGTH", 16384)
        req_timeout = self._get_httpx_timeout(timeout)

        await self.check_ollama_health(selected_model)

        payload = {
            "model": selected_model,
            "messages": messages,
            "stream": True,
            "options": {
                "num_ctx": num_ctx
            },
            "keep_alive": "15m",
        }

        t_queued = time.time()
        logger.info(f"[OLLAMA REQUEST QUEUED] model='{selected_model}' num_ctx={num_ctx} endpoint='{self.endpoint}'")

        lock = self._get_lock()
        acquired = False
        try:
            try:
                await asyncio.wait_for(lock.acquire(), timeout=10.0)
                acquired = True
            except asyncio.TimeoutError:
                logger.warning(f"[OLLAMA LOCK TIMEOUT] Lock acquisition timed out after 10.0s for '{selected_model}'. Proceeding without lock.")

            t_acquired = time.time()
            lock_wait_ms = (t_acquired - t_queued) * 1000.0

            t_http_start = time.time()
            full_chunks = []
            eval_count = 0
            headers_received_ms = 0.0
            first_token_ms = 0.0
            headers_logged = False

            try:
                async with httpx.AsyncClient(timeout=req_timeout) as client:
                    async with client.stream("POST", self.endpoint, json=payload) as response:
                        t_headers = time.time()
                        headers_received_ms = (t_headers - t_http_start) * 1000.0

                        if response.status_code == 404:
                            raise LLMProviderError("ollama", f"Model '{selected_model}' not found on Ollama server.")
                        elif response.status_code != 200:
                            content = await response.aread()
                            raise LLMProviderError("ollama", f"HTTP {response.status_code}: {content.decode()}")

                        async for line in response.aiter_lines():
                            line = line.strip()
                            if not line:
                                continue
                            try:
                                data = json.loads(line)
                            except json.JSONDecodeError:
                                continue

                            msg_data = data.get("message", {})
                            chunk = msg_data.get("content") or data.get("thinking") or msg_data.get("thinking") or ""
                            eval_count = data.get("eval_count") or eval_count

                            if chunk:
                                if not headers_logged:
                                    first_token_ms = (time.time() - t_http_start) * 1000.0
                                    headers_logged = True
                                full_chunks.append(chunk)

                            if data.get("done", False):
                                break

                t_total = (time.time() - t_queued) * 1000.0
                content = "".join(full_chunks)
                logger.info(
                    f"[OLLAMA TIMING DIAGNOSTICS] model='{selected_model}' lock_wait_ms={lock_wait_ms:.1f}ms "
                    f"headers_ms={headers_received_ms:.1f}ms first_token_ms={first_token_ms:.1f}ms "
                    f"total_ms={t_total:.1f}ms eval_tokens={eval_count} chars={len(content)}"
                )
                return content

            except httpx.TimeoutException as exc:
                t_duration = time.time() - t_queued
                logger.error(f"[OLLAMA LLM TIMEOUT] model='{selected_model}' num_ctx={num_ctx} duration_s={t_duration:.2f}s error='{type(exc).__name__}: {str(exc)}'")
                raise LLMTimeoutError("ollama")
            except LLMProviderError:
                raise
            except httpx.RequestError as exc:
                t_duration = time.time() - t_queued
                logger.error(f"[OLLAMA LLM REQUEST ERROR] model='{selected_model}' duration_s={t_duration:.2f}s error='{type(exc).__name__}: {str(exc)}'")
                raise LLMProviderError(
                    "ollama", f"Ollama server is unavailable at {self.base_url}: {str(exc)}"
                )
        finally:
            if acquired:
                lock.release()

    async def generate_response_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
        cancel_event: Optional[asyncio.Event] = None,
    ) -> AsyncGenerator[str, None]:
        selected_model = model or settings.OLLAMA_MODEL
        num_ctx = getattr(settings, "OLLAMA_CONTEXT_LENGTH", 16384)
        req_timeout = self._get_httpx_timeout(timeout)

        await self.check_ollama_health(selected_model)

        payload = {
            "model": selected_model,
            "messages": messages,
            "stream": True,
            "options": {
                "num_ctx": num_ctx
            },
            "keep_alive": "15m",
        }

        t_queued = time.time()
        logger.info(f"[OLLAMA STREAM QUEUED] model='{selected_model}' num_ctx={num_ctx}")

        lock = self._get_lock()
        acquired = False
        try:
            try:
                await asyncio.wait_for(lock.acquire(), timeout=10.0)
                acquired = True
            except asyncio.TimeoutError:
                logger.warning(f"[OLLAMA STREAM LOCK TIMEOUT] Could not acquire lock within 10s for '{selected_model}'. Proceeding.")

            t_acquired = time.time()
            lock_wait_ms = (t_acquired - t_queued) * 1000.0

            t_http_start = time.time()
            headers_received_ms = 0.0
            first_token_ms = 0.0
            first_chunk_logged = False
            chunk_count = 0
            char_count = 0

            try:
                async with httpx.AsyncClient(timeout=req_timeout) as client:
                    async with client.stream("POST", self.endpoint, json=payload) as response:
                        t_headers = time.time()
                        headers_received_ms = (t_headers - t_http_start) * 1000.0

                        if response.status_code == 404:
                            raise LLMProviderError("ollama", f"Model '{selected_model}' not found on Ollama server.")
                        elif response.status_code != 200:
                            content = await response.aread()
                            raise LLMProviderError("ollama", f"HTTP {response.status_code}: {content.decode()}")

                        async for line in response.aiter_lines():
                            if cancel_event and cancel_event.is_set():
                                elapsed_ms = (time.time() - t_queued) * 1000.0
                                logger.info(f"[OLLAMA CANCEL] reason=barge_in elapsed_ms={elapsed_ms:.1f}ms chunks={chunk_count}")
                                await response.aclose()
                                raise asyncio.CancelledError("Ollama generation cancelled via barge-in")

                            line = line.strip()
                            if not line:
                                continue
                            try:
                                data = json.loads(line)
                            except json.JSONDecodeError:
                                continue

                            msg_data = data.get("message", {})
                            chunk = msg_data.get("content") or data.get("thinking") or msg_data.get("thinking") or ""

                            if chunk:
                                if not first_chunk_logged:
                                    first_token_ms = (time.time() - t_http_start) * 1000.0
                                    logger.info(f"[OLLAMA STREAM TTFT] headers_ms={headers_received_ms:.1f}ms first_token_ms={first_token_ms:.1f}ms")
                                    first_chunk_logged = True
                                chunk_count += 1
                                char_count += len(chunk)
                                yield chunk

                            if data.get("done", False):
                                break

                t_total = (time.time() - t_queued) * 1000.0
                logger.info(
                    f"[OLLAMA STREAM SUCCESS] lock_wait_ms={lock_wait_ms:.1f}ms headers_ms={headers_received_ms:.1f}ms "
                    f"first_token_ms={first_token_ms:.1f}ms total_ms={t_total:.1f}ms chunks={chunk_count} chars={char_count}"
                )

            except httpx.TimeoutException as exc:
                t_duration = time.time() - t_queued
                logger.error(f"[OLLAMA STREAM TIMEOUT] model='{selected_model}' num_ctx={num_ctx} duration_s={t_duration:.2f}s error='{type(exc).__name__}: {str(exc)}'")
                raise LLMTimeoutError("ollama")
            except LLMProviderError:
                raise
            except httpx.RequestError as exc:
                t_duration = time.time() - t_queued
                logger.error(f"[OLLAMA STREAM REQUEST ERROR] duration_s={t_duration:.2f}s error='{type(exc).__name__}: {str(exc)}'")
                raise LLMProviderError(
                    "ollama", f"Ollama server is unavailable at {self.base_url}: {str(exc)}"
                )
        finally:
            if acquired:
                lock.release()


class LLMManager:
    """Factory and router for LLM Provider instances."""

    _providers = {
        "mock": MockLLMProvider,
        "openai": OpenAILLMProvider,
        "gemini": GeminiLLMProvider,
        "ollama": OllamaLLMProvider,
    }

    def __init__(self, provider_name: Optional[str] = None):
        self.provider_name = (provider_name or settings.LLM_PROVIDER).lower()
        self.provider = self._get_provider(self.provider_name)

    def _get_provider(self, provider_name: str) -> LLMProvider:
        provider_cls = self._providers.get(provider_name)
        if not provider_cls:
            logger.warning(f"Unknown provider '{provider_name}'. Falling back to MockLLMProvider.")
            return MockLLMProvider()
        return provider_cls()

    async def generate(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> str:
        """Routes text generation call to the configured provider."""
        return await self.provider.generate_response(messages, model=model, timeout=timeout)

    async def generate_stream(
        self,
        messages: List[Dict[str, str]],
        model: Optional[str] = None,
        timeout: Optional[float] = None,
        cancel_event: Optional[asyncio.Event] = None,
    ) -> AsyncGenerator[str, None]:
        """Routes text generation streaming call to the configured provider."""
        async for chunk in self.provider.generate_response_stream(messages, model=model, timeout=timeout, cancel_event=cancel_event):
            yield chunk
